# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\2020EQ\CODE\LED\module\frm_led.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txt_data = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_data.setObjectName("txt_data")
        self.verticalLayout_3.addWidget(self.txt_data)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.txt_dbip = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbip.sizePolicy().hasHeightForWidth())
        self.txt_dbip.setSizePolicy(sizePolicy)
        self.txt_dbip.setObjectName("txt_dbip")
        self.horizontalLayout_5.addWidget(self.txt_dbip)
        self.port = QtWidgets.QLabel(self.centralwidget)
        self.port.setObjectName("port")
        self.horizontalLayout_5.addWidget(self.port)
        self.txt_dbport = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbport.sizePolicy().hasHeightForWidth())
        self.txt_dbport.setSizePolicy(sizePolicy)
        self.txt_dbport.setObjectName("txt_dbport")
        self.horizontalLayout_5.addWidget(self.txt_dbport)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.txt_dbuser = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbuser.sizePolicy().hasHeightForWidth())
        self.txt_dbuser.setSizePolicy(sizePolicy)
        self.txt_dbuser.setObjectName("txt_dbuser")
        self.horizontalLayout_5.addWidget(self.txt_dbuser)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.txt_dbpwd = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbpwd.sizePolicy().hasHeightForWidth())
        self.txt_dbpwd.setSizePolicy(sizePolicy)
        self.txt_dbpwd.setObjectName("txt_dbpwd")
        self.horizontalLayout_5.addWidget(self.txt_dbpwd)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.txt_dbdatabase = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbdatabase.sizePolicy().hasHeightForWidth())
        self.txt_dbdatabase.setSizePolicy(sizePolicy)
        self.txt_dbdatabase.setObjectName("txt_dbdatabase")
        self.horizontalLayout_5.addWidget(self.txt_dbdatabase)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tbv_title = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_title.sizePolicy().hasHeightForWidth())
        self.tbv_title.setSizePolicy(sizePolicy)
        self.tbv_title.setMinimumSize(QtCore.QSize(0, 50))
        self.tbv_title.setObjectName("tbv_title")
        self.horizontalLayout_4.addWidget(self.tbv_title)
        spacerItem = QtWidgets.QSpacerItem(7, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.gb_command = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_command.setObjectName("gb_command")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gb_command)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_black = QtWidgets.QPushButton(self.gb_command)
        self.btn_black.setObjectName("btn_black")
        self.verticalLayout_2.addWidget(self.btn_black)
        self.btn_testled = QtWidgets.QPushButton(self.gb_command)
        self.btn_testled.setObjectName("btn_testled")
        self.verticalLayout_2.addWidget(self.btn_testled)
        self.btn_dbtest = QtWidgets.QPushButton(self.gb_command)
        self.btn_dbtest.setObjectName("btn_dbtest")
        self.verticalLayout_2.addWidget(self.btn_dbtest)
        self.btn_testudp = QtWidgets.QPushButton(self.gb_command)
        self.btn_testudp.setObjectName("btn_testudp")
        self.verticalLayout_2.addWidget(self.btn_testudp)
        self.btn_timer = QtWidgets.QPushButton(self.gb_command)
        self.btn_timer.setObjectName("btn_timer")
        self.verticalLayout_2.addWidget(self.btn_timer)
        self.horizontalLayout_4.addWidget(self.gb_command)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txt_ip = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ip.sizePolicy().hasHeightForWidth())
        self.txt_ip.setSizePolicy(sizePolicy)
        self.txt_ip.setObjectName("txt_ip")
        self.horizontalLayout_3.addWidget(self.txt_ip)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txt_port = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_port.sizePolicy().hasHeightForWidth())
        self.txt_port.setSizePolicy(sizePolicy)
        self.txt_port.setObjectName("txt_port")
        self.horizontalLayout_3.addWidget(self.txt_port)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdo_welcome = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_welcome.setObjectName("rdo_welcome")
        self.verticalLayout.addWidget(self.rdo_welcome)
        self.rdo_judge = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_judge.setObjectName("rdo_judge")
        self.verticalLayout.addWidget(self.rdo_judge)
        self.rdo_schedule = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_schedule.setObjectName("rdo_schedule")
        self.verticalLayout.addWidget(self.rdo_schedule)
        self.rdo_startlist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_startlist.setObjectName("rdo_startlist")
        self.verticalLayout.addWidget(self.rdo_startlist)
        self.rdo_result = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_result.setObjectName("rdo_result")
        self.verticalLayout.addWidget(self.rdo_result)
        self.rdo_step = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_step.setObjectName("rdo_step")
        self.verticalLayout.addWidget(self.rdo_step)
        self.rdo_resultlist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_resultlist.setObjectName("rdo_resultlist")
        self.verticalLayout.addWidget(self.rdo_resultlist)
        self.rdo_ranklist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_ranklist.setObjectName("rdo_ranklist")
        self.verticalLayout.addWidget(self.rdo_ranklist)
        self.rdo_medal = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_medal.setObjectName("rdo_medal")
        self.verticalLayout.addWidget(self.rdo_medal)
        self.rdo_celebrate = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_celebrate.setObjectName("rdo_celebrate")
        self.verticalLayout.addWidget(self.rdo_celebrate)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.trv_event = QtWidgets.QTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trv_event.sizePolicy().hasHeightForWidth())
        self.trv_event.setSizePolicy(sizePolicy)
        self.trv_event.setMinimumSize(QtCore.QSize(100, 0))
        self.trv_event.setObjectName("trv_event")
        self.trv_event.header().setDefaultSectionSize(150)
        self.horizontalLayout.addWidget(self.trv_event)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.tbv_data = QtWidgets.QTableView(self.centralwidget)
        self.tbv_data.setObjectName("tbv_data")
        self.horizontalLayout.addWidget(self.tbv_data)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.btn_ok = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "IP:"))
        self.port.setText(_translate("MainWindow", "port:"))
        self.label_5.setText(_translate("MainWindow", "user:"))
        self.label_6.setText(_translate("MainWindow", "pwd:"))
        self.label_4.setText(_translate("MainWindow", "database:"))
        self.gb_command.setTitle(_translate("MainWindow", "指令栏"))
        self.btn_black.setText(_translate("MainWindow", "黑屏"))
        self.btn_testled.setText(_translate("MainWindow", "测试屏"))
        self.btn_dbtest.setText(_translate("MainWindow", "测试数据库"))
        self.btn_testudp.setText(_translate("MainWindow", "测试UDP"))
        self.btn_timer.setText(_translate("MainWindow", "倒计时"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.label_2.setText(_translate("MainWindow", "PORT:"))
        self.rdo_welcome.setText(_translate("MainWindow", "欢迎屏"))
        self.rdo_judge.setText(_translate("MainWindow", "裁判屏"))
        self.rdo_schedule.setText(_translate("MainWindow", "赛程屏"))
        self.rdo_startlist.setText(_translate("MainWindow", "秩序单"))
        self.rdo_result.setText(_translate("MainWindow", "成绩屏"))
        self.rdo_step.setText(_translate("MainWindow", "步伐屏"))
        self.rdo_resultlist.setText(_translate("MainWindow", "成绩排名"))
        self.rdo_ranklist.setText(_translate("MainWindow", "名次排名"))
        self.rdo_medal.setText(_translate("MainWindow", "奖牌屏"))
        self.rdo_celebrate.setText(_translate("MainWindow", "庆典屏"))
        self.btn_ok.setText(_translate("MainWindow", "确定"))
        self.btn_cancel.setText(_translate("MainWindow", "退出"))
