# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\2020EQ\CODE\LED\module\frm_led.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_data = QtWidgets.QTextEdit(self.tab_3)
        self.txt_data.setObjectName("txt_data")
        self.horizontalLayout_2.addWidget(self.txt_data)
        self.tbv_register = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_register.sizePolicy().hasHeightForWidth())
        self.tbv_register.setSizePolicy(sizePolicy)
        self.tbv_register.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_register.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_register.setObjectName("tbv_register")
        self.tbv_register.setColumnCount(0)
        self.tbv_register.setRowCount(0)
        self.tbv_register.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_register.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_register.horizontalHeader().setStretchLastSection(True)
        self.tbv_register.verticalHeader().setSortIndicatorShown(True)
        self.tbv_register.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tbv_register)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 270))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdo_welcome = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_welcome.setObjectName("rdo_welcome")
        self.verticalLayout.addWidget(self.rdo_welcome)
        self.rdo_judge = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_judge.setObjectName("rdo_judge")
        self.verticalLayout.addWidget(self.rdo_judge)
        self.rdo_schedule = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_schedule.setObjectName("rdo_schedule")
        self.verticalLayout.addWidget(self.rdo_schedule)
        self.rdo_startlist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_startlist.setObjectName("rdo_startlist")
        self.verticalLayout.addWidget(self.rdo_startlist)
        self.rdo_result = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_result.setObjectName("rdo_result")
        self.verticalLayout.addWidget(self.rdo_result)
        self.rdo_step = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_step.setObjectName("rdo_step")
        self.verticalLayout.addWidget(self.rdo_step)
        self.rdo_resultlist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_resultlist.setObjectName("rdo_resultlist")
        self.verticalLayout.addWidget(self.rdo_resultlist)
        self.rdo_ranklist = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_ranklist.setObjectName("rdo_ranklist")
        self.verticalLayout.addWidget(self.rdo_ranklist)
        self.rdo_medal = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_medal.setObjectName("rdo_medal")
        self.verticalLayout.addWidget(self.rdo_medal)
        self.rdo_celebrate = QtWidgets.QRadioButton(self.groupBox)
        self.rdo_celebrate.setObjectName("rdo_celebrate")
        self.verticalLayout.addWidget(self.rdo_celebrate)
        self.btn_ok = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.txt_dbip = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbip.sizePolicy().hasHeightForWidth())
        self.txt_dbip.setSizePolicy(sizePolicy)
        self.txt_dbip.setObjectName("txt_dbip")
        self.horizontalLayout_9.addWidget(self.txt_dbip)
        self.port = QtWidgets.QLabel(self.tab_3)
        self.port.setObjectName("port")
        self.horizontalLayout_9.addWidget(self.port)
        self.txt_dbport = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbport.sizePolicy().hasHeightForWidth())
        self.txt_dbport.setSizePolicy(sizePolicy)
        self.txt_dbport.setObjectName("txt_dbport")
        self.horizontalLayout_9.addWidget(self.txt_dbport)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.txt_dbuser = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbuser.sizePolicy().hasHeightForWidth())
        self.txt_dbuser.setSizePolicy(sizePolicy)
        self.txt_dbuser.setObjectName("txt_dbuser")
        self.horizontalLayout_9.addWidget(self.txt_dbuser)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.txt_dbpwd = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbpwd.sizePolicy().hasHeightForWidth())
        self.txt_dbpwd.setSizePolicy(sizePolicy)
        self.txt_dbpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_dbpwd.setObjectName("txt_dbpwd")
        self.horizontalLayout_9.addWidget(self.txt_dbpwd)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.txt_dbdatabase = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbdatabase.sizePolicy().hasHeightForWidth())
        self.txt_dbdatabase.setSizePolicy(sizePolicy)
        self.txt_dbdatabase.setObjectName("txt_dbdatabase")
        self.horizontalLayout_9.addWidget(self.txt_dbdatabase)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbv_title = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_title.sizePolicy().hasHeightForWidth())
        self.tbv_title.setSizePolicy(sizePolicy)
        self.tbv_title.setMinimumSize(QtCore.QSize(0, 100))
        self.tbv_title.setObjectName("tbv_title")
        self.tbv_title.setColumnCount(0)
        self.tbv_title.setRowCount(0)
        self.horizontalLayout.addWidget(self.tbv_title)
        self.groupbox = QtWidgets.QGroupBox(self.tab_3)
        self.groupbox.setObjectName("groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupbox)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ckb_timer = QtWidgets.QCheckBox(self.groupbox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_timer.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_timer.setFont(font)
        self.ckb_timer.setObjectName("ckb_timer")
        self.verticalLayout_3.addWidget(self.ckb_timer)
        self.ckb_matchselected = QtWidgets.QCheckBox(self.groupbox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_matchselected.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_matchselected.setFont(font)
        self.ckb_matchselected.setObjectName("ckb_matchselected")
        self.verticalLayout_3.addWidget(self.ckb_matchselected)
        self.horizontalLayout.addWidget(self.groupbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.txt_ip = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ip.sizePolicy().hasHeightForWidth())
        self.txt_ip.setSizePolicy(sizePolicy)
        self.txt_ip.setObjectName("txt_ip")
        self.horizontalLayout_7.addWidget(self.txt_ip)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.txt_port = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_port.sizePolicy().hasHeightForWidth())
        self.txt_port.setSizePolicy(sizePolicy)
        self.txt_port.setObjectName("txt_port")
        self.horizontalLayout_7.addWidget(self.txt_port)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gb_command = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_command.sizePolicy().hasHeightForWidth())
        self.gb_command.setSizePolicy(sizePolicy)
        self.gb_command.setMinimumSize(QtCore.QSize(100, 0))
        self.gb_command.setObjectName("gb_command")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_command)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_black = QtWidgets.QPushButton(self.gb_command)
        self.btn_black.setObjectName("btn_black")
        self.verticalLayout_4.addWidget(self.btn_black)
        self.btn_testled = QtWidgets.QPushButton(self.gb_command)
        self.btn_testled.setObjectName("btn_testled")
        self.verticalLayout_4.addWidget(self.btn_testled)
        self.btn_dbtest = QtWidgets.QPushButton(self.gb_command)
        self.btn_dbtest.setObjectName("btn_dbtest")
        self.verticalLayout_4.addWidget(self.btn_dbtest)
        self.btn_testudp = QtWidgets.QPushButton(self.gb_command)
        self.btn_testudp.setObjectName("btn_testudp")
        self.verticalLayout_4.addWidget(self.btn_testudp)
        self.horizontalLayout_10.addWidget(self.gb_command)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.trv_event = QtWidgets.QTreeWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trv_event.sizePolicy().hasHeightForWidth())
        self.trv_event.setSizePolicy(sizePolicy)
        self.trv_event.setMinimumSize(QtCore.QSize(100, 0))
        self.trv_event.setObjectName("trv_event")
        self.trv_event.headerItem().setText(0, "1")
        self.trv_event.header().setVisible(True)
        self.horizontalLayout_10.addWidget(self.trv_event)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.tbv_data = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_data.sizePolicy().hasHeightForWidth())
        self.tbv_data.setSizePolicy(sizePolicy)
        self.tbv_data.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_data.setObjectName("tbv_data")
        self.tbv_data.setColumnCount(0)
        self.tbv_data.setRowCount(0)
        self.tbv_data.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_data.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_data.horizontalHeader().setStretchLastSection(True)
        self.tbv_data.verticalHeader().setSortIndicatorShown(True)
        self.tbv_data.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_10.addWidget(self.tbv_data)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.btn_cancel = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_8.addWidget(self.btn_cancel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rdo_welcome.setText(_translate("MainWindow", "欢迎屏"))
        self.rdo_judge.setText(_translate("MainWindow", "裁判屏"))
        self.rdo_schedule.setText(_translate("MainWindow", "赛程屏"))
        self.rdo_startlist.setText(_translate("MainWindow", "秩序单"))
        self.rdo_result.setText(_translate("MainWindow", "成绩屏"))
        self.rdo_step.setText(_translate("MainWindow", "步伐屏"))
        self.rdo_resultlist.setText(_translate("MainWindow", "成绩排名"))
        self.rdo_ranklist.setText(_translate("MainWindow", "名次排名"))
        self.rdo_medal.setText(_translate("MainWindow", "奖牌屏"))
        self.rdo_celebrate.setText(_translate("MainWindow", "庆典屏"))
        self.btn_ok.setText(_translate("MainWindow", "发送"))
        self.label_9.setText(_translate("MainWindow", "IP:"))
        self.port.setText(_translate("MainWindow", "port:"))
        self.label_10.setText(_translate("MainWindow", "user:"))
        self.label_11.setText(_translate("MainWindow", "pwd:"))
        self.label_12.setText(_translate("MainWindow", "database:"))
        self.groupbox.setTitle(_translate("MainWindow", "命令栏"))
        self.ckb_timer.setText(_translate("MainWindow", "倒计时"))
        self.ckb_matchselected.setText(_translate("MainWindow", "项目锁定"))
        self.label_7.setText(_translate("MainWindow", "IP:"))
        self.label_8.setText(_translate("MainWindow", "PORT:"))
        self.gb_command.setTitle(_translate("MainWindow", "指令栏"))
        self.btn_black.setText(_translate("MainWindow", "黑屏"))
        self.btn_testled.setText(_translate("MainWindow", "测试屏"))
        self.btn_dbtest.setText(_translate("MainWindow", "测试数据库"))
        self.btn_testudp.setText(_translate("MainWindow", "测试UDP"))
        self.btn_cancel.setText(_translate("MainWindow", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "LED控制"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "数据库初始化"))
