# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\2020EQ\CODE\LED\module\frm_led.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.trv_event = QtWidgets.QTreeWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trv_event.sizePolicy().hasHeightForWidth())
        self.trv_event.setSizePolicy(sizePolicy)
        self.trv_event.setMinimumSize(QtCore.QSize(100, 0))
        self.trv_event.setObjectName("trv_event")
        self.trv_event.headerItem().setText(0, "1")
        self.trv_event.header().setVisible(True)
        self.horizontalLayout_10.addWidget(self.trv_event)
        self.tbv_data = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_data.sizePolicy().hasHeightForWidth())
        self.tbv_data.setSizePolicy(sizePolicy)
        self.tbv_data.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_data.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_data.setObjectName("tbv_data")
        self.tbv_data.setColumnCount(0)
        self.tbv_data.setRowCount(0)
        self.tbv_data.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_data.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_data.horizontalHeader().setStretchLastSection(True)
        self.tbv_data.verticalHeader().setSortIndicatorShown(True)
        self.tbv_data.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_10.addWidget(self.tbv_data)
        self.gb_command = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_command.sizePolicy().hasHeightForWidth())
        self.gb_command.setSizePolicy(sizePolicy)
        self.gb_command.setMinimumSize(QtCore.QSize(100, 0))
        self.gb_command.setObjectName("gb_command")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gb_command)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_black = QtWidgets.QPushButton(self.gb_command)
        self.btn_black.setObjectName("btn_black")
        self.verticalLayout_4.addWidget(self.btn_black)
        self.btn_testled = QtWidgets.QPushButton(self.gb_command)
        self.btn_testled.setObjectName("btn_testled")
        self.verticalLayout_4.addWidget(self.btn_testled)
        self.btn_dbtest = QtWidgets.QPushButton(self.gb_command)
        self.btn_dbtest.setObjectName("btn_dbtest")
        self.verticalLayout_4.addWidget(self.btn_dbtest)
        self.btn_testudp = QtWidgets.QPushButton(self.gb_command)
        self.btn_testudp.setObjectName("btn_testudp")
        self.verticalLayout_4.addWidget(self.btn_testudp)
        self.horizontalLayout_10.addWidget(self.gb_command)
        self.verticalLayout_26.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.txt_dbip = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbip.sizePolicy().hasHeightForWidth())
        self.txt_dbip.setSizePolicy(sizePolicy)
        self.txt_dbip.setObjectName("txt_dbip")
        self.horizontalLayout_9.addWidget(self.txt_dbip)
        self.port = QtWidgets.QLabel(self.tab_3)
        self.port.setObjectName("port")
        self.horizontalLayout_9.addWidget(self.port)
        self.txt_dbport = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbport.sizePolicy().hasHeightForWidth())
        self.txt_dbport.setSizePolicy(sizePolicy)
        self.txt_dbport.setObjectName("txt_dbport")
        self.horizontalLayout_9.addWidget(self.txt_dbport)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.txt_dbuser = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbuser.sizePolicy().hasHeightForWidth())
        self.txt_dbuser.setSizePolicy(sizePolicy)
        self.txt_dbuser.setObjectName("txt_dbuser")
        self.horizontalLayout_9.addWidget(self.txt_dbuser)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.txt_dbpwd = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbpwd.sizePolicy().hasHeightForWidth())
        self.txt_dbpwd.setSizePolicy(sizePolicy)
        self.txt_dbpwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_dbpwd.setObjectName("txt_dbpwd")
        self.horizontalLayout_9.addWidget(self.txt_dbpwd)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.txt_dbdatabase = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbdatabase.sizePolicy().hasHeightForWidth())
        self.txt_dbdatabase.setSizePolicy(sizePolicy)
        self.txt_dbdatabase.setObjectName("txt_dbdatabase")
        self.horizontalLayout_9.addWidget(self.txt_dbdatabase)
        self.verticalLayout_26.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.tbv_title = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_title.sizePolicy().hasHeightForWidth())
        self.tbv_title.setSizePolicy(sizePolicy)
        self.tbv_title.setMinimumSize(QtCore.QSize(0, 80))
        self.tbv_title.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_title.setObjectName("tbv_title")
        self.tbv_title.setColumnCount(0)
        self.tbv_title.setRowCount(0)
        self.horizontalLayout_38.addWidget(self.tbv_title)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ckb_matchselected = QtWidgets.QCheckBox(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_matchselected.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_matchselected.setFont(font)
        self.ckb_matchselected.setObjectName("ckb_matchselected")
        self.verticalLayout_3.addWidget(self.ckb_matchselected)
        self.horizontalLayout_38.addWidget(self.groupBox)
        self.verticalLayout_26.addLayout(self.horizontalLayout_38)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rd_five_reset = QtWidgets.QRadioButton(self.groupBox_13)
        self.rd_five_reset.setCheckable(True)
        self.rd_five_reset.setChecked(False)
        self.rd_five_reset.setObjectName("rd_five_reset")
        self.gridLayout_2.addWidget(self.rd_five_reset, 0, 0, 1, 1)
        self.rd_five_clear = QtWidgets.QRadioButton(self.groupBox_13)
        self.rd_five_clear.setObjectName("rd_five_clear")
        self.gridLayout_2.addWidget(self.rd_five_clear, 2, 0, 1, 1)
        self.rd_five_start = QtWidgets.QRadioButton(self.groupBox_13)
        self.rd_five_start.setObjectName("rd_five_start")
        self.gridLayout_2.addWidget(self.rd_five_start, 0, 1, 1, 1)
        self.rd_five_stop = QtWidgets.QRadioButton(self.groupBox_13)
        self.rd_five_stop.setObjectName("rd_five_stop")
        self.gridLayout_2.addWidget(self.rd_five_stop, 2, 1, 1, 1)
        self.txt_fivetime = QtWidgets.QLineEdit(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_fivetime.sizePolicy().hasHeightForWidth())
        self.txt_fivetime.setSizePolicy(sizePolicy)
        self.txt_fivetime.setMinimumSize(QtCore.QSize(10, 0))
        self.txt_fivetime.setObjectName("txt_fivetime")
        self.gridLayout_2.addWidget(self.txt_fivetime, 0, 2, 3, 1)
        self.horizontalLayout.addWidget(self.groupBox_13)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_12.sizePolicy().hasHeightForWidth())
        self.groupBox_12.setSizePolicy(sizePolicy)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout.setObjectName("gridLayout")
        self.rd_twenty_clear = QtWidgets.QRadioButton(self.groupBox_12)
        self.rd_twenty_clear.setObjectName("rd_twenty_clear")
        self.gridLayout.addWidget(self.rd_twenty_clear, 2, 0, 1, 1)
        self.rd_twenty_start = QtWidgets.QRadioButton(self.groupBox_12)
        self.rd_twenty_start.setObjectName("rd_twenty_start")
        self.gridLayout.addWidget(self.rd_twenty_start, 1, 1, 1, 1)
        self.rd_twenty_stop = QtWidgets.QRadioButton(self.groupBox_12)
        self.rd_twenty_stop.setObjectName("rd_twenty_stop")
        self.gridLayout.addWidget(self.rd_twenty_stop, 2, 1, 1, 1)
        self.rd_twenty_reset = QtWidgets.QRadioButton(self.groupBox_12)
        self.rd_twenty_reset.setCheckable(True)
        self.rd_twenty_reset.setChecked(False)
        self.rd_twenty_reset.setObjectName("rd_twenty_reset")
        self.gridLayout.addWidget(self.rd_twenty_reset, 1, 0, 1, 1)
        self.txt_twentytime = QtWidgets.QLineEdit(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_twentytime.sizePolicy().hasHeightForWidth())
        self.txt_twentytime.setSizePolicy(sizePolicy)
        self.txt_twentytime.setObjectName("txt_twentytime")
        self.gridLayout.addWidget(self.txt_twentytime, 1, 2, 2, 1)
        self.horizontalLayout.addWidget(self.groupBox_12)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_14.sizePolicy().hasHeightForWidth())
        self.groupBox_14.setSizePolicy(sizePolicy)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rd_scrolling_start = QtWidgets.QRadioButton(self.groupBox_14)
        self.rd_scrolling_start.setCheckable(True)
        self.rd_scrolling_start.setChecked(False)
        self.rd_scrolling_start.setObjectName("rd_scrolling_start")
        self.gridLayout_3.addWidget(self.rd_scrolling_start, 0, 0, 1, 1)
        self.rd_scrolling_stop = QtWidgets.QRadioButton(self.groupBox_14)
        self.rd_scrolling_stop.setObjectName("rd_scrolling_stop")
        self.gridLayout_3.addWidget(self.rd_scrolling_stop, 1, 0, 1, 1)
        self.txt_scrollingtime = QtWidgets.QLineEdit(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_scrollingtime.sizePolicy().hasHeightForWidth())
        self.txt_scrollingtime.setSizePolicy(sizePolicy)
        self.txt_scrollingtime.setObjectName("txt_scrollingtime")
        self.gridLayout_3.addWidget(self.txt_scrollingtime, 0, 1, 2, 1)
        self.horizontalLayout.addWidget(self.groupBox_14)
        self.verticalLayout_26.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_data = QtWidgets.QTextEdit(self.tab_3)
        self.txt_data.setObjectName("txt_data")
        self.horizontalLayout_2.addWidget(self.txt_data)
        self.tbv_register = QtWidgets.QTableWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_register.sizePolicy().hasHeightForWidth())
        self.tbv_register.setSizePolicy(sizePolicy)
        self.tbv_register.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_register.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_register.setObjectName("tbv_register")
        self.tbv_register.setColumnCount(0)
        self.tbv_register.setRowCount(0)
        self.tbv_register.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_register.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_register.horizontalHeader().setStretchLastSection(True)
        self.tbv_register.verticalHeader().setSortIndicatorShown(True)
        self.tbv_register.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tbv_register)
        self.groupBox1 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(100, 270))
        self.groupBox1.setTitle("")
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdo_welcome = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_welcome.setObjectName("rdo_welcome")
        self.verticalLayout.addWidget(self.rdo_welcome)
        self.rdo_judge = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_judge.setObjectName("rdo_judge")
        self.verticalLayout.addWidget(self.rdo_judge)
        self.rdo_schedule = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_schedule.setObjectName("rdo_schedule")
        self.verticalLayout.addWidget(self.rdo_schedule)
        self.rdo_startlist = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_startlist.setObjectName("rdo_startlist")
        self.verticalLayout.addWidget(self.rdo_startlist)
        self.rdo_result = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_result.setObjectName("rdo_result")
        self.verticalLayout.addWidget(self.rdo_result)
        self.rdo_step = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_step.setObjectName("rdo_step")
        self.verticalLayout.addWidget(self.rdo_step)
        self.rdo_resultlist = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_resultlist.setObjectName("rdo_resultlist")
        self.verticalLayout.addWidget(self.rdo_resultlist)
        self.rdo_ranklist = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_ranklist.setObjectName("rdo_ranklist")
        self.verticalLayout.addWidget(self.rdo_ranklist)
        self.rdo_medal = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_medal.setObjectName("rdo_medal")
        self.verticalLayout.addWidget(self.rdo_medal)
        self.rdo_celebrate = QtWidgets.QRadioButton(self.groupBox1)
        self.rdo_celebrate.setObjectName("rdo_celebrate")
        self.verticalLayout.addWidget(self.rdo_celebrate)
        self.btn_ok = QtWidgets.QPushButton(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_ok.setCheckable(False)
        self.btn_ok.setChecked(False)
        self.btn_ok.setObjectName("btn_ok")
        self.verticalLayout.addWidget(self.btn_ok)
        self.horizontalLayout_2.addWidget(self.groupBox1)
        self.verticalLayout_26.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.txt_ip = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_ip.sizePolicy().hasHeightForWidth())
        self.txt_ip.setSizePolicy(sizePolicy)
        self.txt_ip.setObjectName("txt_ip")
        self.horizontalLayout_7.addWidget(self.txt_ip)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.txt_port = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_port.sizePolicy().hasHeightForWidth())
        self.txt_port.setSizePolicy(sizePolicy)
        self.txt_port.setObjectName("txt_port")
        self.horizontalLayout_7.addWidget(self.txt_port)
        self.verticalLayout_26.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_cancel = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_8.addWidget(self.btn_cancel)
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.verticalLayout_26.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tbv_file = QtWidgets.QTableWidget(self.tab_4)
        self.tbv_file.setObjectName("tbv_file")
        self.tbv_file.setColumnCount(0)
        self.tbv_file.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tbv_file)
        self.gb_command_2 = QtWidgets.QGroupBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_command_2.sizePolicy().hasHeightForWidth())
        self.gb_command_2.setSizePolicy(sizePolicy)
        self.gb_command_2.setMinimumSize(QtCore.QSize(100, 0))
        self.gb_command_2.setObjectName("gb_command_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.gb_command_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.btn_file = QtWidgets.QPushButton(self.gb_command_2)
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout_11.addWidget(self.btn_file)
        self.btn_dosql = QtWidgets.QPushButton(self.gb_command_2)
        self.btn_dosql.setObjectName("btn_dosql")
        self.horizontalLayout_11.addWidget(self.btn_dosql)
        self.verticalLayout_6.addWidget(self.gb_command_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.txt_dbip_2 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbip_2.sizePolicy().hasHeightForWidth())
        self.txt_dbip_2.setSizePolicy(sizePolicy)
        self.txt_dbip_2.setObjectName("txt_dbip_2")
        self.horizontalLayout_14.addWidget(self.txt_dbip_2)
        self.port_2 = QtWidgets.QLabel(self.tab_4)
        self.port_2.setObjectName("port_2")
        self.horizontalLayout_14.addWidget(self.port_2)
        self.txt_dbport_2 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbport_2.sizePolicy().hasHeightForWidth())
        self.txt_dbport_2.setSizePolicy(sizePolicy)
        self.txt_dbport_2.setObjectName("txt_dbport_2")
        self.horizontalLayout_14.addWidget(self.txt_dbport_2)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.txt_dbuser_2 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbuser_2.sizePolicy().hasHeightForWidth())
        self.txt_dbuser_2.setSizePolicy(sizePolicy)
        self.txt_dbuser_2.setObjectName("txt_dbuser_2")
        self.horizontalLayout_14.addWidget(self.txt_dbuser_2)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_14.addWidget(self.label_17)
        self.txt_dbpwd_2 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbpwd_2.sizePolicy().hasHeightForWidth())
        self.txt_dbpwd_2.setSizePolicy(sizePolicy)
        self.txt_dbpwd_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_dbpwd_2.setObjectName("txt_dbpwd_2")
        self.horizontalLayout_14.addWidget(self.txt_dbpwd_2)
        self.label_18 = QtWidgets.QLabel(self.tab_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.txt_dbdatabase_2 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_dbdatabase_2.sizePolicy().hasHeightForWidth())
        self.txt_dbdatabase_2.setSizePolicy(sizePolicy)
        self.txt_dbdatabase_2.setObjectName("txt_dbdatabase_2")
        self.horizontalLayout_14.addWidget(self.txt_dbdatabase_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tbv_register_4 = QtWidgets.QTableWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_register_4.sizePolicy().hasHeightForWidth())
        self.tbv_register_4.setSizePolicy(sizePolicy)
        self.tbv_register_4.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_register_4.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_register_4.setObjectName("tbv_register_4")
        self.tbv_register_4.setColumnCount(0)
        self.tbv_register_4.setRowCount(0)
        self.tbv_register_4.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_register_4.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_register_4.horizontalHeader().setStretchLastSection(True)
        self.tbv_register_4.verticalHeader().setSortIndicatorShown(True)
        self.tbv_register_4.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.tbv_register_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbv_result = QtWidgets.QTableWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_result.sizePolicy().hasHeightForWidth())
        self.tbv_result.setSizePolicy(sizePolicy)
        self.tbv_result.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_result.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_result.setObjectName("tbv_result")
        self.tbv_result.setColumnCount(0)
        self.tbv_result.setRowCount(0)
        self.tbv_result.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_result.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_result.horizontalHeader().setStretchLastSection(True)
        self.tbv_result.verticalHeader().setSortIndicatorShown(True)
        self.tbv_result.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tbv_result)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.trv_event_3 = QtWidgets.QTreeWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trv_event_3.sizePolicy().hasHeightForWidth())
        self.trv_event_3.setSizePolicy(sizePolicy)
        self.trv_event_3.setMinimumSize(QtCore.QSize(100, 0))
        self.trv_event_3.setObjectName("trv_event_3")
        self.trv_event_3.headerItem().setText(0, "1")
        self.trv_event_3.header().setVisible(False)
        self.horizontalLayout_17.addWidget(self.trv_event_3)
        self.tbv_data_3 = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_data_3.sizePolicy().hasHeightForWidth())
        self.tbv_data_3.setSizePolicy(sizePolicy)
        self.tbv_data_3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_data_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_data_3.setObjectName("tbv_data_3")
        self.tbv_data_3.setColumnCount(0)
        self.tbv_data_3.setRowCount(0)
        self.tbv_data_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_data_3.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_data_3.horizontalHeader().setStretchLastSection(True)
        self.tbv_data_3.verticalHeader().setSortIndicatorShown(True)
        self.tbv_data_3.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_17.addWidget(self.tbv_data_3)
        self.gb_command_3 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_command_3.sizePolicy().hasHeightForWidth())
        self.gb_command_3.setSizePolicy(sizePolicy)
        self.gb_command_3.setMinimumSize(QtCore.QSize(100, 0))
        self.gb_command_3.setObjectName("gb_command_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gb_command_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.btn_black_3 = QtWidgets.QPushButton(self.gb_command_3)
        self.btn_black_3.setObjectName("btn_black_3")
        self.verticalLayout_10.addWidget(self.btn_black_3)
        self.btn_testled_3 = QtWidgets.QPushButton(self.gb_command_3)
        self.btn_testled_3.setObjectName("btn_testled_3")
        self.verticalLayout_10.addWidget(self.btn_testled_3)
        self.btn_dbtest_3 = QtWidgets.QPushButton(self.gb_command_3)
        self.btn_dbtest_3.setObjectName("btn_dbtest_3")
        self.verticalLayout_10.addWidget(self.btn_dbtest_3)
        self.btn_testudp_3 = QtWidgets.QPushButton(self.gb_command_3)
        self.btn_testudp_3.setObjectName("btn_testudp_3")
        self.verticalLayout_10.addWidget(self.btn_testudp_3)
        self.horizontalLayout_17.addWidget(self.gb_command_3)
        self.verticalLayout_12.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tbv_title_3 = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_title_3.sizePolicy().hasHeightForWidth())
        self.tbv_title_3.setSizePolicy(sizePolicy)
        self.tbv_title_3.setMinimumSize(QtCore.QSize(0, 100))
        self.tbv_title_3.setObjectName("tbv_title_3")
        self.tbv_title_3.setColumnCount(0)
        self.tbv_title_3.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.tbv_title_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ckb_matchselected_3 = QtWidgets.QCheckBox(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_matchselected_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_matchselected_3.setFont(font)
        self.ckb_matchselected_3.setObjectName("ckb_matchselected_3")
        self.verticalLayout_11.addWidget(self.ckb_matchselected_3)
        self.ckb_five_3 = QtWidgets.QCheckBox(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_five_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_five_3.setFont(font)
        self.ckb_five_3.setObjectName("ckb_five_3")
        self.verticalLayout_11.addWidget(self.ckb_five_3)
        self.ckb_twenty_3 = QtWidgets.QCheckBox(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_twenty_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_twenty_3.setFont(font)
        self.ckb_twenty_3.setObjectName("ckb_twenty_3")
        self.verticalLayout_11.addWidget(self.ckb_twenty_3)
        self.ckb_scrolling_3 = QtWidgets.QCheckBox(self.groupBox_5)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.ckb_scrolling_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.ckb_scrolling_3.setFont(font)
        self.ckb_scrolling_3.setObjectName("ckb_scrolling_3")
        self.verticalLayout_11.addWidget(self.ckb_scrolling_3)
        self.horizontalLayout_6.addWidget(self.groupBox_5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txt_data_3 = QtWidgets.QTextEdit(self.tab)
        self.txt_data_3.setObjectName("txt_data_3")
        self.horizontalLayout_5.addWidget(self.txt_data_3)
        self.tbv_register_3 = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbv_register_3.sizePolicy().hasHeightForWidth())
        self.tbv_register_3.setSizePolicy(sizePolicy)
        self.tbv_register_3.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbv_register_3.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbv_register_3.setObjectName("tbv_register_3")
        self.tbv_register_3.setColumnCount(0)
        self.tbv_register_3.setRowCount(0)
        self.tbv_register_3.horizontalHeader().setCascadingSectionResizes(True)
        self.tbv_register_3.horizontalHeader().setSortIndicatorShown(True)
        self.tbv_register_3.horizontalHeader().setStretchLastSection(True)
        self.tbv_register_3.verticalHeader().setSortIndicatorShown(True)
        self.tbv_register_3.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_5.addWidget(self.tbv_register_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(100, 270))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rdo_welcome_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_welcome_3.setObjectName("rdo_welcome_3")
        self.verticalLayout_9.addWidget(self.rdo_welcome_3)
        self.rdo_judge_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_judge_3.setObjectName("rdo_judge_3")
        self.verticalLayout_9.addWidget(self.rdo_judge_3)
        self.rdo_schedule_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_schedule_3.setObjectName("rdo_schedule_3")
        self.verticalLayout_9.addWidget(self.rdo_schedule_3)
        self.rdo_startlist_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_startlist_3.setObjectName("rdo_startlist_3")
        self.verticalLayout_9.addWidget(self.rdo_startlist_3)
        self.rdo_result_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_result_3.setObjectName("rdo_result_3")
        self.verticalLayout_9.addWidget(self.rdo_result_3)
        self.rdo_step_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_step_3.setObjectName("rdo_step_3")
        self.verticalLayout_9.addWidget(self.rdo_step_3)
        self.rdo_resultlist_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_resultlist_3.setObjectName("rdo_resultlist_3")
        self.verticalLayout_9.addWidget(self.rdo_resultlist_3)
        self.rdo_ranklist_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_ranklist_3.setObjectName("rdo_ranklist_3")
        self.verticalLayout_9.addWidget(self.rdo_ranklist_3)
        self.rdo_medal_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_medal_3.setObjectName("rdo_medal_3")
        self.verticalLayout_9.addWidget(self.rdo_medal_3)
        self.rdo_celebrate_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.rdo_celebrate_3.setObjectName("rdo_celebrate_3")
        self.verticalLayout_9.addWidget(self.rdo_celebrate_3)
        self.btn_ok_3 = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok_3.sizePolicy().hasHeightForWidth())
        self.btn_ok_3.setSizePolicy(sizePolicy)
        self.btn_ok_3.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_ok_3.setCheckable(False)
        self.btn_ok_3.setChecked(False)
        self.btn_ok_3.setObjectName("btn_ok_3")
        self.verticalLayout_9.addWidget(self.btn_ok_3)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gb_command.setTitle(_translate("MainWindow", "指令栏"))
        self.btn_black.setText(_translate("MainWindow", "黑屏"))
        self.btn_testled.setText(_translate("MainWindow", "测试屏"))
        self.btn_dbtest.setText(_translate("MainWindow", "测试数据库"))
        self.btn_testudp.setText(_translate("MainWindow", "测试UDP"))
        self.label_9.setText(_translate("MainWindow", "IP:"))
        self.port.setText(_translate("MainWindow", "port:"))
        self.label_10.setText(_translate("MainWindow", "user:"))
        self.label_11.setText(_translate("MainWindow", "pwd:"))
        self.label_12.setText(_translate("MainWindow", "database:"))
        self.groupBox.setTitle(_translate("MainWindow", "命令栏"))
        self.ckb_matchselected.setText(_translate("MainWindow", "项目锁定"))
        self.groupBox_13.setTitle(_translate("MainWindow", "正计时钟"))
        self.rd_five_reset.setText(_translate("MainWindow", "复位"))
        self.rd_five_clear.setText(_translate("MainWindow", "清屏"))
        self.rd_five_start.setText(_translate("MainWindow", "开始"))
        self.rd_five_stop.setText(_translate("MainWindow", "暂停"))
        self.groupBox_12.setTitle(_translate("MainWindow", "倒计时钟"))
        self.rd_twenty_clear.setText(_translate("MainWindow", "清屏"))
        self.rd_twenty_start.setText(_translate("MainWindow", "开始"))
        self.rd_twenty_stop.setText(_translate("MainWindow", "暂停"))
        self.rd_twenty_reset.setText(_translate("MainWindow", "复位"))
        self.groupBox_14.setTitle(_translate("MainWindow", "列表滚动"))
        self.rd_scrolling_start.setText(_translate("MainWindow", "开始"))
        self.rd_scrolling_stop.setText(_translate("MainWindow", "暂停"))
        self.rdo_welcome.setText(_translate("MainWindow", "欢迎屏"))
        self.rdo_judge.setText(_translate("MainWindow", "裁判屏"))
        self.rdo_schedule.setText(_translate("MainWindow", "赛程屏"))
        self.rdo_startlist.setText(_translate("MainWindow", "秩序单"))
        self.rdo_result.setText(_translate("MainWindow", "成绩屏"))
        self.rdo_step.setText(_translate("MainWindow", "步伐屏"))
        self.rdo_resultlist.setText(_translate("MainWindow", "成绩排名"))
        self.rdo_ranklist.setText(_translate("MainWindow", "名次排名"))
        self.rdo_medal.setText(_translate("MainWindow", "奖牌屏"))
        self.rdo_celebrate.setText(_translate("MainWindow", "庆典屏"))
        self.btn_ok.setText(_translate("MainWindow", "发送"))
        self.label_7.setText(_translate("MainWindow", "IP:"))
        self.label_8.setText(_translate("MainWindow", "PORT:"))
        self.btn_cancel.setText(_translate("MainWindow", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "LED控制"))
        self.gb_command_2.setTitle(_translate("MainWindow", "指令栏"))
        self.btn_file.setText(_translate("MainWindow", "选择文件"))
        self.btn_dosql.setText(_translate("MainWindow", "导入数据库"))
        self.label_15.setText(_translate("MainWindow", "IP:"))
        self.port_2.setText(_translate("MainWindow", "port:"))
        self.label_16.setText(_translate("MainWindow", "user:"))
        self.label_17.setText(_translate("MainWindow", "pwd:"))
        self.label_18.setText(_translate("MainWindow", "database:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "数据库初始化"))
        self.gb_command_3.setTitle(_translate("MainWindow", "指令栏"))
        self.btn_black_3.setText(_translate("MainWindow", "黑屏"))
        self.btn_testled_3.setText(_translate("MainWindow", "测试屏"))
        self.btn_dbtest_3.setText(_translate("MainWindow", "测试数据库"))
        self.btn_testudp_3.setText(_translate("MainWindow", "测试UDP"))
        self.groupBox_5.setTitle(_translate("MainWindow", "命令栏"))
        self.ckb_matchselected_3.setText(_translate("MainWindow", "项目锁定"))
        self.ckb_five_3.setText(_translate("MainWindow", "正计时钟"))
        self.ckb_twenty_3.setText(_translate("MainWindow", "倒计时钟"))
        self.ckb_scrolling_3.setText(_translate("MainWindow", "滚屏启停"))
        self.rdo_welcome_3.setText(_translate("MainWindow", "欢迎屏"))
        self.rdo_judge_3.setText(_translate("MainWindow", "裁判屏"))
        self.rdo_schedule_3.setText(_translate("MainWindow", "赛程屏"))
        self.rdo_startlist_3.setText(_translate("MainWindow", "秩序单"))
        self.rdo_result_3.setText(_translate("MainWindow", "成绩屏"))
        self.rdo_step_3.setText(_translate("MainWindow", "步伐屏"))
        self.rdo_resultlist_3.setText(_translate("MainWindow", "成绩排名"))
        self.rdo_ranklist_3.setText(_translate("MainWindow", "名次排名"))
        self.rdo_medal_3.setText(_translate("MainWindow", "奖牌屏"))
        self.rdo_celebrate_3.setText(_translate("MainWindow", "庆典屏"))
        self.btn_ok_3.setText(_translate("MainWindow", "发送"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "报表打印"))
