# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\2020EQ\CODE\LED\module\frm_display.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(876, 611)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fra_top = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fra_top.sizePolicy().hasHeightForWidth())
        self.fra_top.setSizePolicy(sizePolicy)
        self.fra_top.setMinimumSize(QtCore.QSize(0, 100))
        self.fra_top.setAutoFillBackground(False)
        self.fra_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fra_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fra_top.setLineWidth(0)
        self.fra_top.setObjectName("fra_top")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fra_top)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ly_top = QtWidgets.QHBoxLayout()
        self.ly_top.setSpacing(0)
        self.ly_top.setObjectName("ly_top")
        self.horizontalLayout_4.addLayout(self.ly_top)
        self.verticalLayout.addWidget(self.fra_top)
        self.fra_center = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fra_center.sizePolicy().hasHeightForWidth())
        self.fra_center.setSizePolicy(sizePolicy)
        self.fra_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fra_center.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fra_center.setLineWidth(0)
        self.fra_center.setObjectName("fra_center")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fra_center)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ly_center = QtWidgets.QHBoxLayout()
        self.ly_center.setSpacing(0)
        self.ly_center.setObjectName("ly_center")
        self.horizontalLayout_5.addLayout(self.ly_center)
        self.verticalLayout.addWidget(self.fra_center)
        self.fra_bottom = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fra_bottom.sizePolicy().hasHeightForWidth())
        self.fra_bottom.setSizePolicy(sizePolicy)
        self.fra_bottom.setMinimumSize(QtCore.QSize(0, 100))
        self.fra_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fra_bottom.setFrameShadow(QtWidgets.QFrame.Plain)
        self.fra_bottom.setLineWidth(0)
        self.fra_bottom.setObjectName("fra_bottom")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fra_bottom)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ly_bottom = QtWidgets.QHBoxLayout()
        self.ly_bottom.setSpacing(0)
        self.ly_bottom.setObjectName("ly_bottom")
        self.horizontalLayout_6.addLayout(self.ly_bottom)
        self.verticalLayout.addWidget(self.fra_bottom)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
