# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\2020EQ\CODE\LED\module\frm_main.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(647, 545)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_center = QtWidgets.QTabWidget(Form)
        self.tab_center.setObjectName("tab_center")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbwgt_center = QtWidgets.QTableWidget(self.tab)
        self.tbwgt_center.setObjectName("tbwgt_center")
        self.tbwgt_center.setColumnCount(2)
        self.tbwgt_center.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_center.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tbwgt_center.setHorizontalHeaderItem(1, item)
        self.verticalLayout_4.addWidget(self.tbwgt_center)
        self.tab_center.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbwgt_top = QtWidgets.QTableWidget(self.tab_2)
        self.tbwgt_top.setObjectName("tbwgt_top")
        self.tbwgt_top.setColumnCount(2)
        self.tbwgt_top.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_top.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.tbwgt_top)
        self.tab_center.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbwgt_bottom = QtWidgets.QTableWidget(self.tab_3)
        self.tbwgt_bottom.setObjectName("tbwgt_bottom")
        self.tbwgt_bottom.setColumnCount(2)
        self.tbwgt_bottom.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbwgt_bottom.setHorizontalHeaderItem(1, item)
        self.verticalLayout_2.addWidget(self.tbwgt_bottom)
        self.tab_center.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tab_center)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_OK = QtWidgets.QPushButton(Form)
        self.btn_OK.setObjectName("btn_OK")
        self.horizontalLayout.addWidget(self.btn_OK)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_Cancel = QtWidgets.QPushButton(Form)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout.addWidget(self.btn_Cancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tab_center.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tbwgt_center.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tbwgt_center.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tbwgt_center.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tbwgt_center.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tbwgt_center.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tbwgt_center.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tbwgt_center.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tbwgt_center.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tbwgt_center.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tbwgt_center.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tbwgt_center.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tbwgt_center.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tbwgt_center.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tbwgt_center.horizontalHeaderItem(0)
        item.setText(_translate("Form", "tag"))
        item = self.tbwgt_center.horizontalHeaderItem(1)
        item.setText(_translate("Form", "property"))
        self.tab_center.setTabText(self.tab_center.indexOf(self.tab), _translate("Form", " 主窗体"))
        item = self.tbwgt_top.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tbwgt_top.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tbwgt_top.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tbwgt_top.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tbwgt_top.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tbwgt_top.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tbwgt_top.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tbwgt_top.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tbwgt_top.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tbwgt_top.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tbwgt_top.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tbwgt_top.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tbwgt_top.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tbwgt_top.horizontalHeaderItem(0)
        item.setText(_translate("Form", "tag"))
        item = self.tbwgt_top.horizontalHeaderItem(1)
        item.setText(_translate("Form", "property"))
        self.tab_center.setTabText(self.tab_center.indexOf(self.tab_2), _translate("Form", " 顶部窗体"))
        item = self.tbwgt_bottom.verticalHeaderItem(0)
        item.setText(_translate("Form", "1"))
        item = self.tbwgt_bottom.verticalHeaderItem(1)
        item.setText(_translate("Form", "2"))
        item = self.tbwgt_bottom.verticalHeaderItem(2)
        item.setText(_translate("Form", "3"))
        item = self.tbwgt_bottom.verticalHeaderItem(3)
        item.setText(_translate("Form", "4"))
        item = self.tbwgt_bottom.verticalHeaderItem(4)
        item.setText(_translate("Form", "5"))
        item = self.tbwgt_bottom.verticalHeaderItem(5)
        item.setText(_translate("Form", "6"))
        item = self.tbwgt_bottom.verticalHeaderItem(6)
        item.setText(_translate("Form", "7"))
        item = self.tbwgt_bottom.verticalHeaderItem(7)
        item.setText(_translate("Form", "8"))
        item = self.tbwgt_bottom.verticalHeaderItem(8)
        item.setText(_translate("Form", "9"))
        item = self.tbwgt_bottom.verticalHeaderItem(9)
        item.setText(_translate("Form", "10"))
        item = self.tbwgt_bottom.verticalHeaderItem(10)
        item.setText(_translate("Form", "11"))
        item = self.tbwgt_bottom.verticalHeaderItem(11)
        item.setText(_translate("Form", "12"))
        item = self.tbwgt_bottom.verticalHeaderItem(12)
        item.setText(_translate("Form", "13"))
        item = self.tbwgt_bottom.horizontalHeaderItem(0)
        item.setText(_translate("Form", "tag"))
        item = self.tbwgt_bottom.horizontalHeaderItem(1)
        item.setText(_translate("Form", "property"))
        self.tab_center.setTabText(self.tab_center.indexOf(self.tab_3), _translate("Form", "底部窗体"))
        self.btn_OK.setText(_translate("Form", "确定"))
        self.btn_Cancel.setText(_translate("Form", " 退出"))
